#include <stdio.h>
#include <stdlib.h>
#include <time.h>
#include "lexer.h"
#include "parser.h"

int main(int argc, char *argv[])
{
    // The command line argument requires the testcase file and an output file
    // Example: ./stage1exe testcase.txt parsetreeOutFile.txt
    if (argc < 3)
    {
        printf("Usage: ./stage1exe <testcase.txt> <parsetreeOutFile.txt>\n");
        return 1;
    }

    // Required status message at the beginning of execution
    printf("\n[Status] Both lexical and syntax analysis modules implemented.\n");
    printf("[Status] FIRST and FOLLOW sets hardcoded/mapped in table.\n");

    int option;
    do
    {
        printf("\n======================================================\n");
        printf("               Compiler Project Driver                \n");
        printf("======================================================\n");
        printf("0 : For exit\n");
        printf("1 : For removal of comments\n");
        printf("2 : For printing the token list generated by the lexer\n");
        printf("3 : For parsing and verifying syntactic correctness\n");
        printf("4 : For printing the total execution time\n");
        printf("\nEnter option: ");

        if (scanf("%d", &option) != 1)
        {
            printf("Invalid input. Exiting.\n");
            break;
        }

        switch (option)
        {
        case 0:
            printf("Exiting compiler...\n");
            break;

        case 1:
        {
            printf("\n--- Comment Free Code ---\n");
            // The driver is required to print the comment-free code to the console
            removeComments(argv[1], "cleanFile.txt");

            FILE *cleanFp = fopen("cleanFile.txt", "r");
            if (cleanFp)
            {
                char c;
                while ((c = fgetc(cleanFp)) != EOF)
                {
                    putchar(c);
                }
                fclose(cleanFp);
            }
            else
            {
                printf("Error opening temporary clean file.\n");
            }
            break;
        }

        case 2:
        {
            FILE *fp = fopen(argv[1], "r");
            if (fp == NULL)
            {
                printf("Error: Could not open file %s\n", argv[1]);
                break;
            }

            // Reset line number so we can run Option 2 multiple times accurately.
            extern int lineNumber; 
            lineNumber = 1;

            twinBuffer B = initBuffer(fp);
            tokenInfo tk;

            printf("\n--- Token List ---\n");
            do
            {
                tk = getNextToken(B);

                // Skip printing TK_ERROR tokens in the formatted list 
                // because getNextToken already prints the specific error message.
                if (tk->tokenType != TK_EOF && tk->tokenType != TK_ERROR)
                {
                    extern const char* tokenStr[]; // Assuming this is defined in your files
                    printf("Line no. %-4d\t Lexeme %-15s\t Token %s\n",
                           tk->lineNo, tk->lexeme, tokenStr[tk->tokenType]);
                }

                TokenType currentType = tk->tokenType;
                free(tk);

                if (currentType == TK_EOF)
                    break;

            } while (1);

            free(B);
            fclose(fp);
            break;
        }

        case 3:
        {
            printf("\n--- Syntax Analysis & Parse Tree Generation ---\n");
            
            // 1. Initialize Sets and Table
            FirstAndFollow F;
            table T;
            ComputeFirstAndFollowSets(&F);
            createParseTable(F, &T);

            // 2. Clear out the old parse tree file so we don't append to a previous run
            FILE *fclear = fopen(argv[2], "w");
            if (fclear) fclose(fclear);

            // Reset lexer globals before parsing
            extern int lineNumber; 
            lineNumber = 1;

            // 3. Run the Parser
            parseTree PT = parseInputSourceCode(argv[1], T);

            // 4. Print the Tree
            if (PT != NULL) {
                printParseTree(PT, argv[2]);
                printf("\nParse tree successfully printed to: %s\n", argv[2]);
            }
            break;
        }

        case 4:
        {
            printf("\n--- Execution Time Measurement ---\n");
            
            clock_t start_time, end_time;
            double total_CPU_time, total_CPU_time_in_seconds;
            
            // Initialize structures needed for parser
            FirstAndFollow F;
            table T;
            ComputeFirstAndFollowSets(&F);
            createParseTable(F, &T);

            extern int lineNumber; 
            lineNumber = 1;

            // Start Timer
            start_time = clock();
            
            // Invoke Lexer and Parser
            parseTree PT = parseInputSourceCode(argv[1], T);
            
            // End Timer
            end_time = clock();

            // Calculate Times
            total_CPU_time = (double) (end_time - start_time);
            total_CPU_time_in_seconds = total_CPU_time / CLOCKS_PER_SEC;
            
            printf("\nTotal CPU time (ticks): %f\n", total_CPU_time);
            printf("Total CPU time in seconds: %f\n", total_CPU_time_in_seconds);
            break;
        }

        default:
            printf("\nInvalid option. Please try again.\n");
        }
    } while (option != 0);

    return 0;
}