/* ID:  2022B3A70404P; Name: Vivek Raj Barnwal */
/* ID:  2022B3A70607P; Name: Abhinav Madaan */
/* ID:  2022B3A70413P; Name: Jayant Grover */
/* ID:  2022B3A70648P; Name: Gathvik Narayan Kolla */
/* ID:  2022B3A70474P; Name: Raghav Mundra */
/* ID: 2023A7PS0653P; Name: Vulli Abhinav */

#include <stdio.h>
#include <stdlib.h>
#include <time.h>
#include "lexer.h"
#include "parser.h"

int main(int argc, char *argv[])
{
    if (argc < 3)
    {
        printf("Usage: ./stage1exe <testcase.txt> <parsetreeOutFile.txt>\n");
        return 1;
    }

    // Displaying status messages as specified in execuation details of driver
    printf("\n[Status] Both lexical and syntax analysis modules implemented.\n");
    printf("[Status] FIRST and FOLLOW sets hardcoded/mapped in table.\n");

    int option;
    do
    {
        printf("[               Compiler Project Driver                ]\n");
        printf("0 : For exit\n");
        printf("1 : For removal of comments\n");
        printf("2 : For printing the token list generated by the lexer\n");
        printf("3 : For parsing and verifying syntactic correctness\n");
        printf("4 : For printing the total execution time\n");
        printf("\nEnter option: ");

        if (scanf("%d", &option) != 1)
        {
            printf("Invalid input. Exiting.\n");
            break;
        }

        switch (option)
        {
        case 0:
            printf("Exiting compiler\n");
            break;

        case 1:
        {
            printf("\n  Comment Free Code   \n");
            removeComments(argv[1], "cleanFile.txt");

            FILE *cleanFp = fopen("cleanFile.txt", "r");
            if (cleanFp)
            {
                char c;
                while ((c = fgetc(cleanFp)) != EOF)
                {
                    putchar(c);
                }
                fclose(cleanFp);
            }
            else
            {
                printf("Error opening temporary clean file.\n");
            }
            break;
        }

        case 2:
        {
            FILE *fp = fopen(argv[1], "r");
            if (fp == NULL)
            {
                printf("Error: Could not open file %s\n", argv[1]);
                break;
            }
            extern int lineNumber; 
            lineNumber = 1;

            twinBuffer B = initBuffer(fp);
            tokenInfo tk;

            printf("\n--- Token List ---\n");
            do
            {
                tk = getNextToken(B);

                // Skip TK_ERROR as getNextToken handles error reporting.
                if (tk->tokenType != TK_EOF && tk->tokenType != TK_ERROR)
                {
                    extern const char* tokenStr[]; 
                    printf("Line no. %-4d\t Lexeme %-15s\t Token %s\n",
                           tk->lineNo, tk->lexeme, tokenStr[tk->tokenType]);
                }

                TokenType currentType = tk->tokenType;
                free(tk);

                if (currentType == TK_EOF)
                    break;

            } while (1);

            free(B);
            fclose(fp);
            break;
        }

        case 3:
        {
            printf("\n   Syntax Analysis & Parse Tree Generation     \n");
            
            FirstAndFollow F;
            table T;
            ComputeFirstAndFollowSets(&F);
            createParseTable(F, &T);

            FILE *fclear = fopen(argv[2], "w");
            if (fclear) fclose(fclear);

            extern int lineNumber; 
            lineNumber = 1;

            parseTree PT = parseInputSourceCode(argv[1], T);

            if (PT != NULL) {
                printParseTree(PT, argv[2]);
                printf("\nParse tree successfully printed to: %s\n", argv[2]);
            }
            break;
        }

        case 4:
        {
            printf("\n  Execution Time Measurement  \n");
            
            clock_t start_time, end_time;
            double total_CPU_time, total_CPU_time_in_seconds;
            
            FirstAndFollow F;
            table T;
            ComputeFirstAndFollowSets(&F);
            createParseTable(F, &T);

            extern int lineNumber; 
            lineNumber = 1;

            start_time = clock();
            
            parseInputSourceCode(argv[1], T);
            
            end_time = clock();

            total_CPU_time = (double) (end_time - start_time);
            total_CPU_time_in_seconds = total_CPU_time / CLOCKS_PER_SEC;
            
            printf("\nTotal CPU time (ticks): %f\n", total_CPU_time);
            printf("Total CPU time in seconds: %f\n", total_CPU_time_in_seconds);
            break;
        }

        default:
            printf("\nInvalid option. Please try again.\n");
        }
    } while (option != 0);

    return 0;
}